on:
  push

name: ci

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
    - run: |
        set -x

        docker version

        docker run --rm hello-world
