on:
  push

name: ci

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Run docker build   
        run: |
          set -x
          docker build -t opencv .
      - 
        name: Run health check   
        run: |
          set -x
          docker run -it --rm -v $(pwd):/work opencv ./health-check.sh

